-- PVM Supabase pricing preparation
-- READ THIS FILE BEFORE EXECUTION.
-- This script creates the new rules table, adds active_days_count, and defines
-- the new tariff trigger function. It does not disable the old trigger, change
-- RLS, or delete any existing object.

BEGIN;

CREATE TABLE IF NOT EXISTS public.pricing_rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    min_daily_sales numeric(14, 2) NOT NULL,
    fee numeric(14, 2) NOT NULL,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pricing_rules_min_daily_sales_nonnegative
        CHECK (min_daily_sales >= 0),
    CONSTRAINT pricing_rules_fee_nonnegative
        CHECK (fee >= 0),
    CONSTRAINT pricing_rules_min_daily_sales_unique
        UNIQUE (min_daily_sales)
);

ALTER TABLE public.pricing
    ADD COLUMN IF NOT EXISTS active_days_count integer;

INSERT INTO public.pricing_rules (min_daily_sales, fee)
VALUES
    (0, 99900),
    (1000000, 99900),
    (2000000, 160000),
    (3000000, 190000),
    (4000000, 220000)
ON CONFLICT (min_daily_sales) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_pricing_rules_active_min_sales
    ON public.pricing_rules (min_daily_sales)
    WHERE active = true;

-- One tariff function. It is intentionally a trigger function so there is no
-- second manual tariff implementation that can drift from the live one.
CREATE OR REPLACE FUNCTION public.calculate_pricing_after_session()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
DECLARE
    v_period_start date;
    v_period_end date;
    v_month_start date;
    v_activation_start date;
    v_total_sales numeric := 0;
    v_sessions_count integer := 0;
    v_active_days_count integer := 0;
    v_average_daily_sales numeric := 0;
    v_fee numeric := 0;
    v_min_fee numeric := 0;
    v_max_fee numeric := 0;
    v_low record;
    v_high record;
BEGIN
    IF NEW.session_date IS NULL THEN
        RETURN NEW;
    END IF;

    -- Closed periods remain historical. A late INSERT for a previous month
    -- does not silently rewrite an old pricing row.
    v_month_start := date_trunc('month', NEW.session_date)::date;
    IF v_month_start < date_trunc('month', current_date)::date THEN
        RETURN NEW;
    END IF;

    v_period_end := (v_month_start + interval '1 month - 1 day')::date;

    SELECT max(
        CASE
            WHEN activation_start ~ '^\d{2}\.\d{2}\.\d{4}$'
            THEN to_date(activation_start, 'DD.MM.YYYY')
            ELSE NULL
        END
    )
    INTO v_activation_start
    FROM public.users
    WHERE login = NEW.login;

    IF v_activation_start IS NOT NULL
       AND v_activation_start >= v_month_start
       AND v_activation_start <= v_period_end THEN
        v_period_start := v_activation_start;
    ELSE
        v_period_start := v_month_start;
    END IF;

    SELECT
        coalesce(sum(sh.total_sales), 0),
        count(*),
        count(DISTINCT sh.session_date::date)
    INTO
        v_total_sales,
        v_sessions_count,
        v_active_days_count
    FROM public.session_history sh
    WHERE sh.login = NEW.login
      AND sh.session_date::date BETWEEN v_period_start AND v_period_end
      AND sh.successful > 0
      AND sh.total_sales > 0;

    v_average_daily_sales := CASE
        WHEN v_active_days_count > 0
        THEN v_total_sales / v_active_days_count
        ELSE 0
    END;

    SELECT min(fee), max(fee)
    INTO v_min_fee, v_max_fee
    FROM public.pricing_rules
    WHERE active = true;

    IF v_min_fee IS NULL OR v_max_fee IS NULL THEN
        RAISE EXCEPTION 'No active pricing rules configured';
    END IF;

    SELECT min_daily_sales, fee
    INTO v_low
    FROM public.pricing_rules
    WHERE active = true
      AND min_daily_sales <= v_average_daily_sales
    ORDER BY min_daily_sales DESC
    LIMIT 1;

    SELECT min_daily_sales, fee
    INTO v_high
    FROM public.pricing_rules
    WHERE active = true
      AND min_daily_sales > v_average_daily_sales
    ORDER BY min_daily_sales ASC
    LIMIT 1;

    IF v_low.min_daily_sales IS NULL THEN
        SELECT min_daily_sales, fee
        INTO v_low
        FROM public.pricing_rules
        WHERE active = true
        ORDER BY min_daily_sales ASC
        LIMIT 1;
    END IF;

    IF v_high.min_daily_sales IS NULL
       OR v_high.min_daily_sales = v_low.min_daily_sales THEN
        v_fee := v_low.fee;
    ELSE
        v_fee := v_low.fee
            + (v_average_daily_sales - v_low.min_daily_sales)
            * (v_high.fee - v_low.fee)
            / (v_high.min_daily_sales - v_low.min_daily_sales);
    END IF;

    v_fee := round(v_fee / 100) * 100;
    v_fee := greatest(v_min_fee, least(v_fee, v_max_fee));

    INSERT INTO public.pricing (
        login,
        month,
        year,
        total_monthly_sales,
        daily_average_sales,
        sessions_count,
        calculated_fee,
        final_fee,
        days_in_period,
        active_days_count,
        period_start,
        period_end,
        updated_at
    )
    VALUES (
        NEW.login,
        extract(month FROM NEW.session_date)::integer,
        extract(year FROM NEW.session_date)::integer,
        v_total_sales,
        v_average_daily_sales,
        v_sessions_count,
        v_fee,
        v_fee,
        v_period_end - v_period_start + 1,
        v_active_days_count,
        v_period_start,
        v_period_end,
        now()
    )
    ON CONFLICT (login, month, year) DO UPDATE SET
        total_monthly_sales = excluded.total_monthly_sales,
        daily_average_sales = excluded.daily_average_sales,
        sessions_count = excluded.sessions_count,
        calculated_fee = excluded.calculated_fee,
        final_fee = excluded.final_fee,
        days_in_period = excluded.days_in_period,
        active_days_count = excluded.active_days_count,
        period_start = excluded.period_start,
        period_end = excluded.period_end,
        updated_at = now();

    RETURN NEW;
END;
$function$;

COMMENT ON TABLE public.pricing_rules IS
    'Editable tariff control points. Ordered by min_daily_sales and linearly interpolated.';

COMMENT ON COLUMN public.pricing.active_days_count IS
    'Unique calendar days with successful sessions and positive total_sales used in the average.';

COMMIT;

-- IMPORTANT:
-- Do not create the new trigger until the cutover script has been reviewed.
-- Running both old and new pricing triggers would perform two calculations.
-- The store-level follow-up in store_activation_prepare.sql replaces this
-- function's period source before cutover. Run that follow-up next.
