# -*- coding: utf-8 -*-
"""
PVM.core - Local Folder Transport
==================================
SyncTransport implementation over a plain local folder (typically a MEGA
synced directory). Files are written atomically (tmp + rename) so the MEGA
client or any other watcher only ever sees complete files.
"""

import os
import tempfile
import time

from sync_transport import SyncTransport


class LocalFolderTransport(SyncTransport):
    """Folder-backed transport: reads/writes files inside a base directory."""

    SUBDIRS = ("outbox", "snapshots", "acks")

    def __init__(self, base_dir: str):
        self.base_dir = os.path.abspath(base_dir) if base_dir else ""
        self._ready = False

    # -- helpers ----------------------------------------------------------
    def _resolve(self, name: str) -> str:
        # Prevent path traversal: names are generated by us (device_key + ts + uuid)
        safe = os.path.basename(name.replace("\\", "/"))
        if name.startswith("outbox/"):
            return os.path.join(self.base_dir, "outbox", safe)
        if name.startswith("snapshots/"):
            return os.path.join(self.base_dir, "snapshots", safe)
        if name.startswith("acks/"):
            return os.path.join(self.base_dir, "acks", safe)
        return os.path.join(self.base_dir, safe)

    def _ensure_subdirs(self) -> bool:
        try:
            os.makedirs(self.base_dir, exist_ok=True)
            for sub in self.SUBDIRS:
                os.makedirs(os.path.join(self.base_dir, sub), exist_ok=True)
            return True
        except Exception:
            return False

    # -- SyncTransport API ------------------------------------------------
    def connect(self) -> bool:
        if not self.base_dir:
            return False
        if not self._ensure_subdirs():
            return False
        probe = os.path.join(self.base_dir, ".pvm_probe")
        try:
            with open(probe, "w", encoding="utf-8") as f:
                f.write("ok")
            with open(probe, "r", encoding="utf-8") as f:
                if f.read() != "ok":
                    return False
            os.remove(probe)
        except Exception:
            return False
        self._ready = True
        return True

    def upload(self, name: str, data: bytes) -> bool:
        path = self._resolve(name)
        if not self._ready and not self.connect():
            return False
        try:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            fd, tmp_path = tempfile.mkstemp(
                prefix=".pvm_tmp_", dir=os.path.dirname(path))
            try:
                with os.fdopen(fd, "wb") as f:
                    f.write(data)
                    f.flush()
                    os.fsync(f.fileno())
                os.replace(tmp_path, path)
            except Exception:
                try:
                    os.remove(tmp_path)
                except Exception:
                    pass
                raise
            return True
        except Exception:
            return False

    def download(self, name: str):
        path = self._resolve(name)
        try:
            with open(path, "rb") as f:
                return f.read()
        except Exception:
            return None

    def list_files(self, prefix: str = "") -> list:
        root = self.base_dir
        if prefix.startswith("outbox/"):
            root = os.path.join(self.base_dir, "outbox")
        elif prefix.startswith("snapshots/"):
            root = os.path.join(self.base_dir, "snapshots")
        elif prefix.startswith("acks/"):
            root = os.path.join(self.base_dir, "acks")
        if not os.path.isdir(root):
            return []
        try:
            names = []
            for fname in sorted(os.listdir(root)):
                fpath = os.path.join(root, fname)
                if os.path.isfile(fpath) and not fname.startswith(".pvm_tmp_"):
                    names.append(fname)
            return names
        except Exception:
            return []

    def delete(self, name: str) -> bool:
        path = self._resolve(name)
        try:
            if os.path.exists(path):
                os.remove(path)
            return True
        except Exception:
            return False

    def stat(self, name: str):
        path = self._resolve(name)
        try:
            st = os.stat(path)
            return (st.st_size, st.st_mtime)
        except Exception:
            return None

    def health(self):
        if not self.base_dir:
            return (False, "Папка не указана")
        if not os.path.isdir(self.base_dir):
            return (False, f"Папка не существует: {self.base_dir}")
        if not os.access(self.base_dir, os.W_OK):
            return (False, "Нет прав на запись в папку")
        if self.connect():
            return (True, f"Папка готова: {self.base_dir}")
        return (False, "Не удалось записать тестовый файл")
