# -*- coding: utf-8 -*-
"""
PVM.core - Localization
=========================
TRANSLATIONS dict and get_text() helper.
Shared by ui.py and all ui_*.py mixin modules.
"""

MODULE_VERSION = globals().get("MODULE_VERSION", "3.11.83")


# =============================================================================
# LOCALIZATION
# =============================================================================
TRANSLATIONS = {
    'en': {
        'app_title': f'PVM.core v{MODULE_VERSION}',
        'activation_status': 'Activation Status',
        'device_key': 'Device Key',
        'device_name': 'Device Name',
        'system_tab': 'System',
        'edit': 'Edit',
        'status': 'Status',
        'period': 'Period',
        'active': 'ACTIVE',
        'inactive': 'INACTIVE',
        'main_tab': 'Main',
        'settings_tab': 'Settings',
        'settings_title': 'Settings',
        'history_tab': 'History',
        'arrival_history_tab': 'Arrival History',
        'audit_qty_rollback': 'Qty Rollback (Audit)',
        'audit_qty_set': 'Qty Set (Audit)',
        'overwritten': 'Overwritten (Sync)',
        'cancellations_tab': 'Cancellations',
        'report_file': 'Report File (XLSX):',
        'browse': 'Browse',
        'login': 'Login:',
        'password': 'Password:',
        'quick_status': 'Quick Status',
        'start_process': 'Start Full Process (Step 1 → Step 2)',
        'stop': 'Stop',
        'operation_log': 'Operation Log',
        'results': 'Results',
        'successful_ids': 'Successful IDs:',
        'failed_attempts': 'Failed Attempts:',
        'failed_after_recovery_attempts': 'Could not process after all recovery attempts',
        'ready': 'Ready',
        'language': 'Language',
        'interface_size': 'Interface Size',
        'font_size': 'Font Size',
        'minimal': 'Minimal',
        'medium': 'Medium',
        'maximum': 'Maximum',
        'automation': 'Automation',
        'scheduled_time': 'Scheduled Time:',
        'auto_download_receipts': 'Auto-download receipts',
        'watch_directory': 'Watch Directory:',
        'enable_scheduler': 'Enable Scheduler',
        'partner_autoblock': 'Partner Auto-Block (PV Bot)',
        'partner_autoblock_all': 'Block: not found in system + insufficient coupons',
        'partner_autoblock_not_found': 'Block only when not found in system',
        'partner_autoblock_insufficient': 'Block only on insufficient coupons',
        'partner_autoblock_off': 'Off (bot never blocks)',
        'shutdown_after': 'Shutdown computer after done',
        'autorun': 'Autorun on system startup',
        'autorun_description': 'When enabled, the application launches automatically when you sign in to your computer.\nThe full application window opens as usual (there is no background/headless mode).',
        'save_settings': 'Save Settings',
        'settings_saved': 'Settings saved successfully!',
        'general': 'General',
        'appearance': 'Appearance',
        'select_directory': 'Select Directory',
        'text_scale': 'Text Scale',
        'bold_prices': 'Bold Prices',
        'show_partner': 'Show Partner',
        'partial_id': 'Partial ID masking',
        'file_pattern': 'File Pattern (today\'s date):',
        'russian': 'Russian',
        'english': 'English',
        'test_now': 'Test Now',
        'dont_show_again': "Don't show again",
        'toast_settings': 'Toast Notifications',
        'toast_size': 'Size',
        'toast_opacity': 'Opacity',
        'toast_position': 'Position',
        'toast_position_top': 'Top',
        'toast_position_bottom': 'Bottom',
        'filtered_tabs_title': 'Hide on Tabs:',
        'filtered_tabs': 'Hide on Tabs',
        'filtered_tabs_desc': 'Notifications will be hidden for selected tabs',
        'toast_type_success': 'Success',
        'toast_type_error': 'Error',
        'toast_type_warning': 'Warning',
        'toast_type_info': 'Info',
        'toast_type_print_success': 'Print Success',
        'toast_type_print_error': 'Print Errors',
        'toast_type_sync': 'Sync Status',
        'toast_type_bot': 'PV Bot Status',
        'toast_type_inventory': 'Products & Inventory',
        'toast_type_sales': 'Sales & Partners',
        'appearance_preview': 'Adaptive Preview',
        'data_updated': 'Data updated',
        'test_description': '(Run scheduler check immediately)',
        'performance': 'Performance',
        'slow_network_mode': 'Slow Network Mode',
        'max_empty_pages': 'Max empty pages',
        'slow_network_description': 'Enable for slow internet (< 5 Mbps) or weak PC.\nIncreases timeouts and adds extra delays for stability.',
        'history_logs': 'History Logs',
        'enable_history': 'Enable session history logging',
        'logs_directory': 'Logs Directory:',
        'open_logs_folder': 'Open Logs Folder',
        'history_description': 'Save detailed reports for each automation session.\nFiles: date_time_loginID_orders.txt',
        'headless_mode': 'Headless Mode (Hidden Browser)',
        'headless_description': 'Run browser in background without visible window.\nUseful when you want to continue working while automation runs.',
        'auto_retry_failed': 'Auto-retry Failed Orders',
        'analytics_tab': 'Analytics',
        'statistics': 'Statistics',
        'biz_period': 'Period',
        'biz_revenue': 'Revenue',
        'biz_cost': 'Cost',
        'biz_profit': 'Net profit',
        'biz_margin': 'Margin',
        'biz_checks': 'Receipts',
        'biz_avg_check': 'Avg receipt',
        'pv_bot_tab': 'PV Bot',
        'auto_retry_description': 'Automatically retry failed orders at the end of the session.\nMay help recover from temporary network issues.',
        'browser_settings': 'Browser Settings',
        'notifications': 'Notifications',
        'no_notifications': 'No notifications',
        'scheduler_short': 'Scheduler',
        'auto_shutdown_short': 'Auto-shutdown',
        'slow_mode_short': 'Slow mode',
        'autorun_short': 'Autorun',
        # Analytics tab
        'analytics_tab': 'Analytics',
        'sync_now': 'Sync Now',
        'repair_inventory': 'Repair Inventory',
        'analytics_summary': 'Summary',
        'total_sessions': 'Total Sessions',
        'total_orders_all': 'Total Orders',
        'success_rate': 'Success Rate',
        'avg_orders_per_day': 'Avg Orders/Day',
        'last_7_days': 'Last 7 Days',
        'last_30_days': 'Last 30 Days',
        'problem_center': 'Problem Center',
        'problem_center_clean': '🟢 No issues',
        'last_scan': 'Last scan:',
        'operations_checked': 'Operations checked:',
        'problem_center_all_ok': '🟢 All operations OK',
        'problem_center_requires_action_one': '🔴 Issue found',
        'problem_center_requires_action_many': '🔴 Issues found',
        'problem_center_current_run': 'Current run: {count} problematic operations',
        'problem_center_partial': '🟡 Partially',
        'problem_center_all_ok_short': '🟢 All OK',
        'problem_center_reason_partner': 'Partner not found',
        'problem_center_reason_stock': 'Out of stock',
        'problem_center_reason_missing': 'Not in DB',
        'problem_center_reason_server': 'Server unavailable',
        'problem_center_reason_retry': '⚠️ Retry needed',
        'problem_center_item_ok': '✅ Processed',
        'problem_center_item_fail': '❌ Failed',
        'pricing_tooltip_title': 'How is the cost calculated?',
        'pricing_tooltip_body': 'The subscription fee is determined automatically based on store activity during the billing period. This approach lets smaller stores pay less and busier stores pay more. The calculation is automatic and cannot be changed manually.',
        'status_pending': 'Pending',
        'status_processing': 'Processing',
        'status_finished': 'Finished',
        'status_failed': 'Failed',
        'status_partial': 'Partial',
        'top_items': 'Top Items',
        'failed_items_chart': 'Often Failed Items',
        'prediction': 'Prediction',
        'predicted_tomorrow': 'Expected Tomorrow',
        'based_on_history': 'Based on your history',
        'alerts': 'Alerts',
        'no_alerts': 'No alerts',
        'alert_low_orders': 'Orders below average today',
        'alert_item_unavailable': 'has been unavailable for',
        'alert_days': 'days',
        'refresh_analytics': 'Refresh',
        'no_data': 'No data yet. Run automation to see analytics.',
        # Client analytics
        'top_clients': 'Top Clients',
        'client_purchases': 'purchases',
        'client_items': 'items',
        'client_spent': 'spent',
        'insufficient_funds_clients': 'Insufficient Funds',
        'no_issues': 'No issues',
        'taxpayer': 'Taxpayer',
        'address': 'Address',
        'separator': 'Separator',
        'datetime': 'Date/Time',
        'cashier': 'Cashier',
        'kkm_info': 'KKM Info',
        'items_table': 'Items Table',
        'partner_info': 'Partner/Client',
        'totals': 'Totals',
        'payment_info': 'Payment',
        'space': 'Space',
        'footer': 'Footer',
        # Popup messages
        'yes': 'Yes',
        'no': 'No',
        'confirm_stop_title': '⚠️ Confirm Stop',
        'confirm_stop_message': 'Are you sure you want to stop the process?',
        'error_no_file_title': '❌ No File Selected',
        'error_no_file_message': 'Please select an Excel report file (.xlsx) before starting.',
        'error_file_not_found_title': '❌ File Not Found',
        'error_file_not_found_message': 'The selected file does not exist:\n{path}',
        # POS System
        'pos_tab': 'Cash Register',
        'pv_bot_tab': 'PV Bot',
        'new_arrival_tab': 'New Arrival',
        'partners_tab': 'Partners',
        'barcode_search': 'Barcode / Search',
        'barcode': 'Barcode',
        'cart': 'Cart',
        'code': 'Code',
        'category': 'Category',
        'name': 'Name',
        'price': 'Price',
        'quantity': 'Qty',
        'discount_pct': 'Discount %',
        'sum': 'Sum',
        'total': 'Total',
        'subtotal': 'Subtotal',
        'received': 'Received',
        'change': 'Change',
        'overpaid': 'Overpaid',
        'invalid_amount': 'Invalid amount',
        'checkout': 'Checkout',
        'cancel': 'Cancel',
        'items_count': 'Items',
        'products_count': 'Products',
        'check_discount': 'Check Discount',
        'buyer': 'Buyer',
        'quick_items': 'Quick Items',
        'add_product': 'Add Product',
        'add_partner': 'Add Partner',
        'product_code': 'Product Code',
        'product_name': 'Product Name',
        'pv_amount': 'PV Amount',
        'purchase_price': 'Purchase Price',
        'sale_price': 'Sale Price (100%)',
        'stock_qty': 'Stock Quantity',
        'save': 'Save',
        'delete': 'Delete',
        'clear': 'Clear',
        'partner_name': 'Partner Name',
        'partner_phone': 'Phone',
        'partner_email': 'Email',
        'partner_notes': 'Notes',
        'partner_discount_info': 'Discount: 50% (fixed)',
        'goods_list': 'Goods List',
        'partners_list': 'Partners (50% discount)',
        'statistics': 'Statistics',
        'total_goods': 'Total goods',
        'stock_value': 'Stock value',
        'receipt_no': 'Receipt #',
        'sale_complete': 'Sale completed!',
        'cart_empty': 'Cart is empty',
        'product_not_found': 'Product not found',
        'no_partners': 'No partners. Add in Partners tab.',
        'select_partner': 'Select Partner',
        'confirm_clear': 'Clear cart?',
        'confirm_delete': 'Delete',
        # Purchases/Arrivals
        'invoice_number': 'Invoice Number',
        'supplier': 'Supplier',
        'purchase_date': 'Date',
        'purchase_items': 'Items in Invoice',
        'purchase_notes': 'Notes',
        'create_writeoff': 'Create Write-off',
        'create_invoice': 'Create Invoice',
        'purchases_list': 'Purchase Invoices',
        'add_to_invoice': 'Add to Invoice',
        'finalize_invoice': 'Finalize Invoice',
        'select_product': 'Select Product',
        'assign_quick_item': 'Assign Quick Item',
        'clear_quick_item': 'Clear',
        'no_goods': 'No goods. Add in New Arrival tab.',
        # Payment methods
        'payment_method': 'Payment Method',
        'cash': 'Cash',
        'card': 'Card',
        'internal': 'Internal',
        'mixed': 'Mixed Payment',
        'cash_amount': 'Cash Amount',
        'card_amount': 'Card Amount',
        'internal_amount': 'Internal Amount',
        'total_to_pay': 'Total to Pay', 
        'remaining': 'Remaining', 
        'confirm': 'Confirm',
        'close': 'Close',
        'cancel': 'Cancel',
        'save': 'Save',
        'not_enough_received': 'Not enough received', 
        'not_enough_mixed': 'Not enough funds (mixed)', # New
        'invalid_amount_format': 'Invalid amount format', # New
        # Sales history
        'sales_tab': 'Sales',
        'sales_history': 'Sales History',
        'receipt_date': 'Date',
        'receipt_number': 'Receipt #',
        'receipt_total': 'Total',
        'receipt_partner': 'Partner',
        'receipt_status': 'Status',
        'completed': 'Completed',
        'refunded': 'Refunded',
        'partial_refund': 'Partial Refund',
        'no_partner': 'No Partner',
        'date_to': 'To',
        'filter_dates': 'Filter',
        'reset_filter': 'Reset',
        'export_sales': 'Export to Excel',
        'receipt_details': 'Receipt Details',
        'payment_info': 'Payment Information',
        'completed': 'Completed',
        'refunded': 'Refunded',
        'no_partner': 'No partner',
        'no_data_for_export': 'No data for export in the selected period',
        'export_success': 'Sales data exported successfully',
        'export_error': 'Error exporting sales data',
        'select_receipt': 'Select a receipt to view details',
        # Sync
        'sync_tab': 'Synchronization',
        'sync_settings': 'Synchronization Settings',
        'sync_master': 'Master register (Server)',
        'sync_standalone': 'Autonomous register',
        'sync_ip': 'Device IP to connect:',
        'sync_connect': 'Connect Device',
        'sync_devices': 'Connected Devices:',
        'sync_secondary': 'Secondary',
        'sync_readonly': 'Read-only',
        'sync_name': 'Device Name:',
        'current_ip': 'Current Device IP:',
        'scan': 'Scan',
        'sync_target_ip': 'Target IP:',
        'data_updated': 'Data updated',
        'sync_folder': 'Sync folder',
        'select_sync_folder': 'Select sync folder',
        'partner': 'Partner',
        'saved': 'saved',
        # History actions
        'action_created': 'Created',
        'action_updated': 'Updated',
        'action_sale': 'Sale',
        'action_restock': 'Restock',
        'action_writeoff': 'Write-off',
        'quantity_upd': 'Quantity Update',
        'action_data_changed': 'Data Changed',
        'creation_date': 'Creation Date',
        'mod_date': 'Mod. Date',
        'calculate': 'Calculate',
        'scale_presets': 'Interface Scale',
        'scale_small': 'Small (80%)',
        'scale_default': 'Standard (87%)',
        'scale_large': 'Large (100%)',
        'scale_manual': 'Manual setup',
        'sale_success': 'Sale completed successfully!',
        'live_bot_queued': '📍 Receipt #{number} queued for Live PV Bot.',
        'live_bot_wait': '⏳ Live Bot: Waiting {delay}s for receipt #{number}...',
        'live_bot_processing': '🚀 Live Bot: Processing receipt #{number}...',
        'live_bot_processed': '✅ Live Bot: Receipt #{number} processed!',
        'live_bot_partial': '⚠️ Live Bot: Receipt #{number} processed partially.',
        'live_bot_failed': '❌ Live Bot: Failed to process receipt #{number}.',
        'live_bot_no_partner': 'Partner ID not found',
        'live_bot_partner_not_found': 'Partner {id} not found',
        'live_bot_item_not_found': 'Item {code} not found in catalog',
        'live_bot_price_mismatch': 'Item {code} price mismatch/out of stock',
        'live_bot_cart_error': 'Cart error: {error}',
        'live_bot_nav_error': 'Navigation error',
        'live_bot_no_items': 'No items added',
        'live_bot_partial_summary': 'Partial success',
        'live_bot_complete': 'COMPLETE',
        'live_bot_manager_started': '🤖 Live PV Bot Manager started.',
        'live_bot_login_failed': '❌ Live Bot: Initial login failed.',
        'live_status_ok': '🤖 Processed by bot',
        'live_status_partial': '🤖 Partially processed',
        'live_status_error': '🤖 Bot error',
        'live_bot_timeout_retry': '🔄 Timeout for #{number}. Added to retry list (wait 2 min).',
        'live_bot_retrying': '🔄 Retrying receipt #{number} (Attempt {count})...',
        # Inventory audit
        'inventory_audit': 'Inventory',
        'inventory_audit_title': 'Inventory Audit',
        'start_new_audit': 'Start New Audit',
        'audit_type_full': 'Full (all goods)',
        'audit_type_filtered': 'Filtered',
        'audit_active': 'Active',
        'audit_completed': 'Completed',
        'audit_cancelled': 'Cancelled',
        'audit_applied': 'Applied',
        'audit_progress': 'Progress',
        'expected_qty': 'Expected',
        'actual_qty': 'Actual',
        'difference': 'Difference',
        'counted': 'Counted',
        'uncounted': 'Uncounted',
        'surplus': 'Surplus',
        'shortage': 'Shortage',
        'matches': 'Matches',
        'discrepancies_only': 'Discrepancies only',
        'finalize_audit': 'Finalize Audit',
        'apply_changes': 'Apply Changes',
        'cancel_audit': 'Cancel Audit',
        'audit_summary': 'Audit Summary',
        'sold_during_audit': 'Sold during audit',
        'adjusted_expected': 'Adjusted expected',
        'net_difference': 'Net difference',
        'audit_confirm_finalize': 'Finalize this audit? Sales during audit will be accounted for.',
        'audit_confirm_apply': 'Apply audit results? Goods quantities will be updated to actual counts.',
        'audit_confirm_cancel': 'Cancel this audit? No changes will be applied.',
        'audit_no_items': 'No items to audit',
        'audit_already_active': 'There is already an active audit. Complete or cancel it first.',
        'quick_count': 'Quick Count',
        'enter_quantity': 'Enter quantity',
        'select_at_least_one': 'Select at least one item',
        'specify_refund_reason': 'Please specify refund reason',
        'error_title': 'Error',
        'warning_title': 'Warning',
        'success_title': 'Success',
        'fill_code_name': 'Fill code and name',
        'check_numeric_values': 'Check numeric values',
        'could_not_cancel_purchase': 'Could not cancel purchase',
        'internal_error': 'Internal Error: Partner ID not found in row tags.',
        'partner_not_found': 'Partner not found in database: {id}',
        'failed_to_open_partner': 'Failed to open partner dialog: {error}',
        'device_renamed': 'Device renamed to: {name}\n(Changes will sync on next cycle)',
        'failed_repair': 'Failed to initiate repair: {error}',
        'logs_missing': 'Logs directory doesn\'t exist.',
        'refreshing_status': 'Refreshing status...',
        'checkout_error_title': 'Checkout Error',
        'checkout_error_msg': 'An error occurred during payment processing:\n{error}\nPlease check logs.',
        'quick_items_exists': 'Product already in quick items!',
        'resume_session_title': 'Resume Session',
        'resume_session_msg': 'Interrupted session found!\n\nFile: {file}\nCompleted: {count} orders\n\nResume from where you left off?',
        'resume_session_badge': 'INTERRUPTED SESSION',
        'resume_session_description': 'An unfinished PV Bot operation was found. You can continue from the last saved point.',
        'resume_session_file': 'Excel report',
        'resume_session_progress': '{completed} of {total} orders completed',
        'resume_session_completed': '{completed} orders completed',
        'resume_session_last_id': 'Last processed ID: {id}',
        'resume_session_question': 'Choose what you want to do with this session:',
        'resume_session_continue': '▶  Continue processing',
        'resume_session_schedule': '⏰  Schedule',
        'resume_session_history': 'View history',
        'resume_session_skip': 'Discard progress',
        'resume_session_skip_title': 'Discard progress',
        'resume_session_skip_message': 'Discard the interrupted session and delete its saved progress?',
        'scanning_network': 'Scanning local network...',
        'no_devices_found': 'No remote devices found',
        'devices_found': 'Found {count} device(s):\n\n{list}\n\nSelect a device?',
        'selected_device': 'Selected: {name}',
        'selected_first_device': 'Found multiple. Selected first: {ip}',
        'restart_title': 'Restart',
        'restart_msg': 'Sync mode or provider changed. Restart app to apply?',
        'settings_saved_toast': 'Settings saved!',
        'error_saving_settings': 'Error saving settings: {error}',
        'rebuild_ui_failed': 'Interface updated partially — restart the application',
        'warehouse_mode_title': 'Warehouse mode',
        'warehouse_mode_msg': 'Sales are disabled on the warehouse device. Use the cashier PC. Warehouse allows: arrivals, goods/partners edits, writeoffs, inventory audits and refunds of existing receipts.',
        'bot_file_not_found_msg': 'No file found with today\'s date ({date}) in:\n{dir}\n\nExpected filename pattern: *{date}*.xlsx',
        'bot_file_not_found_detail': 'No file found with today\'s date ({date}) in:\n{dir}\n\nExpected filename pattern: *{date}*.xlsx\n\nFiles in directory: {files}',
        'cashier_label': 'User',
        'confirm_btn': 'Confirm',
        'technical_works_title': 'TECHNICAL WORKS',
        'automation_unavailable': 'Automation module is unavailable.',
        'scheduler_error_title': 'Scheduler Error',
        'file_found_title': 'File Found',
        'run_automation_now': 'Found file: {file}\n\nRun automation now?',
        'no_watch_dir': 'No watch directory configured!\nPlease set a directory in Settings → Automation.',
        'watch_dir_not_exist': 'Watch directory does not exist:\n{dir}',
        'device_type_title': 'Device Type',
        'choose_device_type': 'Choose this device\'s type',
        'device_type_desc': 'This determines available features and whether the device is the sync server.',
        'cashier_server': 'Cashier (server)',
        'warehouse_receive': 'Warehouse (receive/edit only)',
        'device_type_change_later': '⚠ Can be changed later in Settings → System (requires restart).',
    },
    'ru': {
        'app_title': f'PVM.core v{MODULE_VERSION}',
        'activation_status': 'Статус активации',
        'device_key': 'Ключ устройства',
        'device_name': 'Имя устройства',
        'system_tab': 'Система',
        'status': 'Статус',
        'period': 'Период',
        'active': 'АКТИВЕН',
        'inactive': 'НЕАКТИВЕН',
        'main_tab': 'Главная',
        'settings_tab': 'Настройки',
        'settings_title': 'Настройки',
        'sync_now': 'Синхронизировать',
        'repair_inventory': 'Исправить остатки',
        'report_file': 'Файл отчёта (XLSX):',
        'browse': 'Обзор',
        'login': 'Логин:',
        'password': 'Пароль:',
        'quick_status': 'Быстрый статус',
        'start_process': 'Запустить полный процесс (Шаг 1 → Шаг 2)',
        'stop': 'Стоп',
        'operation_log': 'Журнал операций',
        'results': 'Результаты',
        'successful_ids': 'Успешные ID:',
        'failed_attempts': 'Неудачные попытки:',
        'failed_after_recovery_attempts': 'Не удалось обработать после всех попыток восстановления',
        'ready': 'Готов',
        'language': 'Язык',
        'interface_size': 'Размер интерфейса',
        'font_size': 'Размер шрифта',
        'minimal': 'Минимальный',
        'medium': 'Средний',
        'maximum': 'Максимальный',
        'automation': 'Автоматизация',
        'scheduled_time': 'Запланированное время:',
        'auto_download_receipts': 'Автозагрузка чеков',
        'watch_directory': 'Папка для отслеживания:',
        'enable_scheduler': 'Включить планировщик',
        'partner_autoblock': 'Автоблокировка партнёров (PV Bot)',
        'partner_autoblock_all': 'Блокировать: не найден в системе + недостаточно купонов',
        'partner_autoblock_not_found': 'Блокировать только если не найден в системе',
        'partner_autoblock_insufficient': 'Блокировать только при недостатке купонов',
        'partner_autoblock_off': 'Выключено (бот не блокирует)',
        'shutdown_after': 'Выключить компьютер после завершения',
        'autorun': 'Автозапуск при включении системы',
        'autorun_description': 'При включении приложение запускается автоматически при входе в систему.\nОткрывается обычное окно приложения (фонового/скрытого режима нет).',
        'save_settings': 'Сохранить настройки',
        'settings_saved': 'Настройки успешно сохранены!',
        'general': 'Общие',
        'appearance': 'Оформление',
        'select_directory': 'Выбрать папку',
        'file_pattern': 'Шаблон файла (сегодняшняя дата):',
        'russian': 'Русский',
        'text_scale': 'Масштаб текста',
        'bold_prices': 'Жирные цены',
        'show_partner': 'Отображать партнера',
        'partial_id': 'Скрывать ID (частично)',
        'english': 'Английский',
        'test_now': 'Тест сейчас',
        'dont_show_again': 'Больше не показывать',
        'toast_settings': 'Всплывающие уведомления',
        'toast_size': 'Размер',
        'toast_opacity': 'Прозрачность',
        'toast_position': 'Позиция',
        'toast_position_top': 'Сверху',
        'toast_position_bottom': 'Снизу',
        'filtered_tabs_title': 'Не показывать во вкладках:',
        'filtered_tabs': 'Скрыть на вкладках',
        'filtered_tabs_desc': 'Уведомления будут скрыты для выбранных вкладок',
        'toast_type_success': 'Успех',
        'toast_type_error': 'Ошибка',
        'toast_type_warning': 'Предупреждение',
        'toast_type_info': 'Инфо',
        'toast_type_print_success': 'Печать: Успех',
        'toast_type_print_error': 'Печать: Ошибки',
        'toast_type_sync': 'Синхронизация',
        'toast_type_bot': 'PV Bot: Статус',
        'toast_type_inventory': 'Товары и Остатки',
        'toast_type_sales': 'Продажи и Клиенты',
        'appearance_preview': 'Предпросмотр',
        'data_updated': 'Данные обновлены',
        'test_description': '(Запустить проверку немедленно)',
        'performance': 'Производительность',
        'slow_network_mode': 'Режим медленной сети',
        'max_empty_pages': 'Макс. пустых страниц',
        'slow_network_description': 'Включите для медленного интернета (< 5 Мбит/с) или слабого ПК.\nУвеличивает таймауты и добавляет задержки для стабильности.',
        'history_logs': 'История сессий',
        'logs_directory': 'Папка логов:',
        'open_logs_folder': 'Открыть папку логов',
        'history_description': 'Детальные отчёты сохраняются для каждой сессии.\nФайлы: дата_время_логин_заказы.txt',
        'headless_mode': 'Скрытый режим браузера',
        'headless_description': 'Запускать браузер в фоновом режиме без видимого окна.\nПолезно когда вы хотите продолжать работу во время автоматизации.',
        'auto_retry_failed': 'Авто-повтор неудачных заказов',
        'auto_retry_description': 'Автоматически повторять неудачные заказы в конце сессии.\nМожет помочь при временных проблемах с сетью.',
        'browser_settings': 'Настройки браузера',
        'notifications': 'Уведомления',
        'no_notifications': 'Нет уведомлений',
        'scheduler_short': 'Планировщик',
        'auto_shutdown_short': 'Автовыкл.',
        'slow_mode_short': 'Медл. режим',
        'autorun_short': 'Автозапуск',
        # Analytics tab
        'analytics_tab': 'Аналитика',
        'analytics_summary': 'Сводка',
        'total_sessions': 'Всего сессий',
        'total_orders_all': 'Всего заказов',
        'success_rate': 'Успешность',
        'avg_orders_per_day': 'Среднее в день',
        'last_7_days': 'Последние 7 дней',
        'last_30_days': 'Последние 30 дней',
        'orders_chart': 'Заказы по дням',
        'problem_center': 'Центр проблем',
        'problem_center_clean': '🟢 Проблем нет',
        'last_scan': 'Последнее сканирование:',
        'operations_checked': 'Проверено операций:',
        'problem_center_all_ok': '🟢 Все операции успешно',
        'problem_center_requires_action_one': '🔴 Есть проблема',
        'problem_center_requires_action_many': '🔴 Есть проблемы',
        'problem_center_current_run': 'Текущий запуск: {count} проблемных операций',
        'problem_center_partial': '🟡 Частично',
        'problem_center_all_ok_short': '🟢 Успешно',
        'problem_center_reason_partner': '❌ Партнёр не найден',
        'problem_center_reason_stock': '❌ Нет на складе',
        'problem_center_reason_missing': '❌ Нет в базе',
        'problem_center_reason_server': '❌ Сервер недоступен',
        'problem_center_reason_retry': '⚠️ Нужен повтор',
        'problem_center_item_ok': '✅ Успешно',
        'problem_center_item_fail': '❌ Ошибка',
        'pricing_tooltip_title': 'Как рассчитывается стоимость?',
        'pricing_tooltip_body': 'Размер абонентской платы определяется автоматически на основании активности магазина за расчетный период. Такой подход позволяет небольшим магазинам платить меньше, а более загруженным — больше. Расчет выполняется автоматически и не изменяется вручную.',
        'status_pending': 'В очереди',
        'status_processing': 'В работе',
        'status_finished': 'Завершен',
        'status_failed': 'Ошибка',
        'status_partial': 'Частично',
        'top_items': 'Топ товаров',
        'failed_items_chart': 'Часто недоступные товары',
        'prediction': 'Прогноз',
        'predicted_tomorrow': 'Ожидается завтра',
        'based_on_history': 'На основе вашей истории',
        'alerts': 'Оповещения',
        'no_alerts': 'Нет оповещений',
        'alert_low_orders': 'Заказов меньше обычного сегодня',
        'alert_item_unavailable': 'недоступен уже',
        'alert_days': 'дней',
        'refresh_analytics': 'Обновить',
        'no_data': 'Нет данных. Запустите автоматизацию для отображения аналитики.',
        # Client analytics
        'top_clients': 'Топ клиентов',
        'client_purchases': 'покупок',
        'client_items': 'товаров',
        'client_spent': 'на сумму',
        'insufficient_funds_clients': 'Недостаточно средств',
        'no_issues': 'Нет проблем',
        # Popup messages
        'yes': 'Да',
        'no': 'Нет',
        'confirm_stop_title': '⚠️ Подтверждение',
        'confirm_stop_message': 'Вы уверены, что хотите остановить процесс?',
        'error_no_file_title': '❌ Файл не выбран',
        'error_no_file_message': 'Пожалуйста, выберите файл отчёта Excel (.xlsx) перед запуском.',
        'error_file_not_found_title': '❌ Файл не найден',
        'error_file_not_found_message': 'Выбранный файл не существует:\n{path}',
        # POS System
        'pos_tab': 'Касса',
        'pv_bot_tab': 'PV Бот',
        'new_arrival_tab': 'Склад',
        'history_tab': 'История',
        'arrival_history_tab': 'История приходов',
        'audit_qty_rollback': 'Откат кол-ва (Ревизия)',
        'audit_qty_set': 'Установка кол-ва (Ревизия)',
        'overwritten': 'Перезаписано (Синхр.)',
        'cancellations_tab': 'Отмены',
        'partners_tab': 'Партнеры',
        'device_name': 'Название девайса',
        'edit': 'Редактировать',
        'barcode_search': 'Штрих / Поиск',
        'barcode': 'Штрихкод',
        'cart': 'Корзина',
        'code': 'Код',
        'category': 'Категория',
        'name': 'Наименование',
        'price': 'Цена',
        'quantity': 'Кол-во',
        'discount_pct': 'Скидка %',
        'sum': 'Сумма',
        'total': 'Итог',
        'subtotal': 'Подытог',
        'received': 'Получено',
        'change': 'Сдача',
        'overpaid': 'Переплата',
        'invalid_amount': 'Некорректная сумма',
        'checkout': 'Итог',
        'cancel': 'Отмена',
        'items_count': 'Товаров',
        'products_count': 'Наименований',
        'check_discount': 'Скидка по чеку',
        'buyer': 'Покупатель',
        'quick_items': 'Быстрые товары',
        'add_product': 'Добавить товар',
        'add_partner': 'Добавить партнера',
        'product_code': 'Код товара',
        'product_name': 'Наименование',
        'pv_amount': 'Кол-во ПВ',
        'purchase_price': 'Закупочная цена',
        'sale_price': 'Продажная (100%)',
        'stock_qty': 'Кол-во на складе',
        'save': 'Сохранить',
        'delete': 'Удалить',
        'clear': 'Очистить',
        'partner_name': 'Имя партнера',
        'partner_phone': 'Телефон',
        'partner_email': 'Email',
        'partner_notes': 'Заметки',
        'partner_discount_info': 'Скидка: 50% (фиксированная)',
        'goods_list': 'Список товаров',
        'partners_list': 'Партнеры (скидка 50%)',
        'statistics': 'Статистика',
        'biz_period': 'Период',
        'biz_revenue': 'Выручка',
        'biz_cost': 'Себестоимость',
        'biz_profit': 'Чистая прибыль',
        'biz_margin': 'Маржинальность',
        'biz_checks': 'Чеков',
        'biz_avg_check': 'Средний чек',
        'purchases_history': 'История поступлений',
        'total_goods': 'Всего товаров',
        'stock_value': 'Сумма склада',
        'receipt_no': 'Продажа №',
        'sale_complete': 'Продажа завершена!',
        'cart_empty': 'Корзина пуста',
        'product_not_found': 'Товар не найден',
        'no_partners': 'Нет партнеров. Добавьте в разделе Партнеры.',
        'select_partner': 'Выбор партнера',
        'confirm_clear': 'Очистить корзинy?',
        'confirm_delete': 'Удалить',
        'clear_cart': 'Очистить корзину',
        # Purchases/Arrivals
        'invoice_number': 'Номер накладной',
        'supplier': 'Поставщик',
        'purchase_date': 'Дата',
        'purchase_items': 'Товары в накладной',
        'purchase_total': 'Сумма накладной',
        'purchase_notes': 'Примечания',
        'create_invoice': 'Создать накладную',
        'purchase_notes': 'Примечание',
        'create_writeoff': 'Списание',
        'create_invoice': 'Создать накладную',
        'purchases_list': 'Накладные поступления',
        'add_to_invoice': 'Добавить в накладную',
        'finalize_invoice': 'Подтвердить накладную',
        'clear_quick_item': 'Очистить',
        'no_goods': 'Нет товаров. Добавьте в разделе Склад.',
        # Payment methods
        'payment_method': 'Метод оплаты',
        'cash': 'Наличные',
        'card': 'Карта',
        'internal': 'Внутренний',
        'mixed': 'Смешанная оплата',
        'cash_amount': 'Сумма наличными',
        'card_amount': 'Сумма по карте',
        'internal_amount': 'Сумма с баланса',
        'total_to_pay': 'Сумма к оплате', 
        'remaining': 'Остаток', 
        'confirm': 'Подтвердить',
        'close': 'Закрыть',
        'cancel': 'Отмена',
        'save': 'Сохранить',
        'not_enough_received': 'Недостаточно получено', 
        'not_enough_mixed': 'Недостаточно средств (смешанная)', # New
        'invalid_amount_format': 'Неверный формат суммы', # New
        # Sales history
        'sales_tab': 'Продажи',
        'sales_history': 'История продаж',
        'receipt_date': 'Дата',
        'receipt_number': 'Чек №',
        'receipt_total': 'Сумма',
        'receipt_partner': 'Партнер',
        'receipt_status': 'Статус',
        'date_from': 'С',
        'date_to': 'По',
        'filter_dates': 'Фильтр',
        'reset_filter': 'Сброс',
        'export_sales': 'Экспорт в Excel',
        'receipt_details': 'Детали чека',
        'payment_info': 'Информация об оплате',
        'completed': 'Завершен',
        'refunded': 'Возврат',
        'partial_refund': 'Частичный возврат',
        'no_partner': 'Без партнера',
        'purchases_history': 'История поступлений',
        'writeoff': 'Списание',
        'writeoffs_history': 'История списаний',
        'quantity_upd': 'Обновление кол-ва',
        'action_data_changed': 'Данные изменены',
        'reason': 'Причина',
        'no_data_for_export': 'Нет данных для экспорта в выбранном периоде',
        'export_success': 'Данные продаж успешно экспортированы',
        'export_error': 'Ошибка экспорта данных продаж',
        'select_receipt': 'Выберите чек для просмотра деталей',
        # Sync
        'sync_tab': 'Синхронизация',
        'sync_settings': 'Настройки синхронизации',
        'sync_master': 'Главная касса (сервер)',
        'status': 'Статус',
        'cancel_arrival': 'Отменить закупку',
        'confirm_cancel_arrival': 'Вы уверены, что хотите отменить эту закупку? Инвентарь будет возвращен.',
        'sync_standalone': 'Автономная касса',
        'sync_ip': 'IP адрес устройства для подключения:',
        'sync_connect': 'Подключить устройство',
        'sync_devices': 'Подключённые устройства:',
        'sync_secondary': 'Дочерняя',
        'sync_readonly': 'Только просмотр',
        'sync_name': 'Название устройства:',
        'current_ip': 'IP этого устройства:',
        'scan': 'Поиск',
        'sync_target_ip': 'IP адрес кассы:',
        'data_updated': 'Данные обновлены',
        'sync_folder': 'Папка синхронизации',
        'select_sync_folder': 'Выберите папку синхронизации',
        'partner': 'Партнер',
        'saved': 'сохранено',
        'seller_report': 'Отчет продавца',
        'taxpayer': 'Налогоплательщик',
        'address': 'Адрес',
        'separator': 'Разделитель',
        'datetime': 'Дата/время',
        'cashier': 'Кассир',
        'kkm_info': 'Инфо ККМ',
        'items_table': 'Таблица товаров',
        'partner_info': 'Партнёр/Клиент',
        'totals': 'Итого',
        'payment_info': 'Оплата',
        'space': 'Пробел',
        'footer': 'Подвал',
        # История
        'action_created': 'Создано',
        'action_updated': 'Изменено',
        'action_sale': 'Продажа',
        'action_restock': 'Склад',
        'action_writeoff': 'Списание',
        'creation_date': 'Дата создания',
        'mod_date': 'Дата изменения',
        'calculate': 'Рассчитать',
        'scale_presets': 'Масштаб интерфейса',
        'scale_small': 'Мелкий (80%)',
        'scale_default': 'Стандарт (87%)',
        'scale_large': 'Крупный (100%)',
        'scale_manual': 'Ручная настройка',
        'sale_success': 'Продажа успешно завершена!',
        'live_bot_queued': '📍 Чек #{number} добавлен в очередь Live PV Bot.',
        'live_bot_wait': '⏳ Live Bot: Ожидание {delay}с для чека #{number}...',
        'live_bot_processing': '🚀 Live Bot: Обработка чека #{number}...',
        'live_bot_processed': '✅ Live Bot: Чек #{number} успешно проведен!',
        'live_bot_partial': '⚠️ Live Bot: Чек #{number} проведен частично.',
        'live_bot_failed': '❌ Live Bot: Ошибка при обработке чека #{number}.',
        'live_bot_no_partner': 'ID партнера не найден',
        'live_bot_partner_not_found': 'Партнер {id} не найден',
        'live_bot_item_not_found': 'Товар {code} не найден в каталоге',
        'live_bot_price_mismatch': 'Товар {code} - несовпадение цены или нет в наличии',
        'live_bot_cart_error': 'Ошибка корзины: {error}',
        'live_bot_nav_error': 'Ошибка навигации',
        'live_bot_no_items': 'Ни один товар не добавлен',
        'live_bot_partial_summary': 'Проведено частично',
        'live_bot_complete': 'ЗАВЕРШЕНО',
        'live_bot_manager_started': '🤖 Менеджер Live PV Бота запущен.',
        'live_bot_login_failed': '❌ Live Bot: Ошибка первоначального входа.',
        'live_status_ok': '🤖 Проведён ботом',
        'live_status_partial': '🤖 Проведён частично',
        'live_status_error': '🤖 Ошибка бота',
        'live_bot_timeout_retry': '🔄 Таймаут для #{number}. Добавлен в список повтора (ждем 2 мин).',
        'live_bot_retrying': '🔄 Повторная попытка для чека #{number} (Попытка {count})...',
        # Inventory audit
        'inventory_audit': 'Ревизия',
        'inventory_audit_title': 'Инвентаризация / Ревизия',
        'start_new_audit': 'Начать ревизию',
        'audit_type_full': 'Полная (все товары)',
        'audit_type_filtered': 'Выборочная',
        'audit_active': 'Активна',
        'audit_completed': 'Завершена',
        'audit_cancelled': 'Отменена',
        'audit_applied': 'Применена',
        'audit_progress': 'Прогресс',
        'expected_qty': 'Ожидаемое',
        'actual_qty': 'Фактическое',
        'difference': 'Разница',
        'counted': 'Подсчитано',
        'uncounted': 'Не подсчитано',
        'surplus': 'Излишки',
        'shortage': 'Недостача',
        'matches': 'Совпадения',
        'discrepancies_only': 'Только расхождения',
        'finalize_audit': 'Завершить ревизию',
        'apply_changes': 'Применить изменения',
        'cancel_audit': 'Отменить ревизию',
        'audit_summary': 'Итоги ревизии',
        'sold_during_audit': 'Продано за время ревизии',
        'adjusted_expected': 'Скорр. ожидаемое',
        'net_difference': 'Чистая разница',
        'audit_confirm_finalize': 'Завершить ревизию? Продажи за время ревизии будут учтены.',
        'audit_confirm_apply': 'Применить результаты ревизии? Остатки товаров будут обновлены до фактических.',
        'audit_confirm_cancel': 'Отменить ревизию? Изменения не будут применены.',
        'audit_no_items': 'Нет товаров для ревизии',
        'audit_already_active': 'Уже есть активная ревизия. Завершите или отмените её.',
        'quick_count': 'Быстрый подсчёт',
        'enter_quantity': 'Введите количество',
        'select_at_least_one': 'Выберите хотя бы один товар',
        'specify_refund_reason': 'Укажите причину возврата',
        'error_title': 'Ошибка',
        'warning_title': 'Предупреждение',
        'success_title': 'Успех',
        'fill_code_name': 'Заполните код и название',
        'check_numeric_values': 'Проверьте числовые значения',
        'could_not_cancel_purchase': 'Не удалось отменить закупку',
        'internal_error': 'Внутренняя ошибка: ID партнёра не найден в тегах строки.',
        'partner_not_found': 'Партнёр не найден в БД: {id}',
        'failed_to_open_partner': 'Не удалось открыть карточку партнёра: {error}',
        'device_renamed': 'Устройство переименовано в: {name}\n(Изменения синхронизируются при следующем цикле)',
        'failed_repair': 'Не удалось запустить исправление: {error}',
        'logs_missing': 'Папка логов не существует.',
        'refreshing_status': 'Обновление статуса...',
        'checkout_error_title': 'Ошибка оформления',
        'checkout_error_msg': 'Произошла ошибка при обработке платежа:\n{error}\nПроверьте логи.',
        'quick_items_exists': 'Этот товар уже есть в быстром доступе!',
        'resume_session_title': 'Продолжить сессию',
        'resume_session_msg': 'Найдена прерванная сессия!\n\nФайл: {file}\nВыполнено: {count} заказов\n\nПродолжить с места остановки?',
        'resume_session_badge': 'ПРЕРВАННАЯ СЕССИЯ',
        'resume_session_description': 'Найдена незавершённая операция PV Bot. Можно продолжить с последней сохранённой точки.',
        'resume_session_file': 'Excel-отчёт',
        'resume_session_progress': 'Выполнено заказов: {completed} из {total}',
        'resume_session_completed': 'Выполнено заказов: {completed}',
        'resume_session_last_id': 'Последний обработанный ID: {id}',
        'resume_session_question': 'Выберите действие для этой сессии:',
        'resume_session_continue': '▶  Продолжить обработку',
        'resume_session_schedule': '⏰  Запланировать',
        'resume_session_history': 'Открыть историю',
        'resume_session_skip': 'Удалить прогресс',
        'resume_session_skip_title': 'Удалить прогресс',
        'resume_session_skip_message': 'Удалить прерванную сессию и сохранённый прогресс?',
        'scanning_network': 'Сканирование локальной сети...',
        'no_devices_found': 'Удалённые устройства не найдены',
        'devices_found': 'Найдено {count} устройств(а):\n\n{list}\n\nВыбрать устройство?',
        'selected_device': 'Выбрано: {name}',
        'selected_first_device': 'Найдено несколько. Выбрано первое: {ip}',
        'restart_title': 'Перезапуск',
        'restart_msg': 'Режим или провайдер синхронизации изменён. Перезапустить приложение?',
        'settings_saved_toast': 'Настройки сохранены!',
        'error_saving_settings': 'Ошибка при сохранении настроек: {error}',
        'rebuild_ui_failed': 'Интерфейс обновлён частично — перезапустите приложение',
        'warehouse_mode_title': 'Складской режим',
        'warehouse_mode_msg': 'Продажи отключены на складском устройстве. Используйте кассовый ПК. Склад позволяет: приём товаров, редактирование товаров/партнёров, списания, ревизии и возвраты существующих чеков.',
        'bot_file_not_found_msg': 'Файл с сегодняшней датой ({date}) не найден в:\n{dir}\n\nОжидаемый формат имени: *{date}*.xlsx',
        'bot_file_not_found_detail': 'Файл с сегодняшней датой ({date}) не найден в:\n{dir}\n\nОжидаемый формат имени: *{date}*.xlsx\n\nФайлы в папке: {files}',
        'cashier_label': 'Пользователь',
        'confirm_btn': 'Подтвердить',
        'technical_works_title': 'ТЕХНИЧЕСКИЕ РАБОТЫ',
        'automation_unavailable': 'Модуль автоматизации недоступен.',
        'scheduler_error_title': 'Ошибка планировщика',
        'file_found_title': 'Файл найден',
        'run_automation_now': 'Найден файл: {file}\n\nЗапустить автоматизацию?',
        'no_watch_dir': 'Папка наблюдения не настроена!\nУкажите папку в Настройки → Автоматизация.',
        'watch_dir_not_exist': 'Папка наблюдения не существует:\n{dir}',
        'device_type_title': 'Тип устройства',
        'choose_device_type': 'Выберите тип этого устройства',
        'device_type_desc': 'Это определит, какие функции доступны и будет ли устройство authoritative сервером синхронизации.',
        'cashier_server': 'Касса (сервер)',
        'warehouse_receive': 'Склад (только приём/редактирование)',
        'device_type_change_later': '⚠ Изменить позже можно в Настройки → Система (с перезапуском).',
    }
}

def get_text(key, lang='ru'):
    """Get translated text."""
    return TRANSLATIONS.get(lang, TRANSLATIONS['ru']).get(key, key)
